### ISSUE TITLE
Empty tables use group functions to prompt empty set

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#1079]
Empty tables use group functions to prompt empty set

## Expected Behavior
count(*) => 0

## Current Behavior
empty set

## case
```yaml
  - id: 3
    desc: "表是空的"
    tags: ["TODO","@chengjing,bug,"]
    inputs:
      -
        columns : ["id bigint","c1 string","c2 int","c7 timestamp"]
        indexs: ["index1:c1:c7"]
    sql: select count(c2) as v1,max(c2) as v2,min(c2) as v3,avg(c2) as v4,sum(c2) as v5 from {0};
    expect:
      order: c1
      columns: ["v1 int","v2 int","v3 int","v4 double","v5 bigint"]
      rows:
        - [0,0,0,0,0]
```
