### ISSUE TITLE
in the aggregate statistics operation after filtering, when the filter conditions are not matched, the "max_where" and "min_where" display results are abnormal

### ISSUE THREAD

**Issue by yabg-shuai666** [4paradigm/OpenMLDB#1295]
Test environment: cluster, Mac ,online
The reproduction process is as follows:
      1.  create table t1 (id bigint, uid string, mid string, cardno string, trans_time timestamp, trans_amt double, trans_type string,        province string ,city string, label bool);
<img width="947" alt="image" src="https://user-images.githubusercontent.com/59086688/155272312-42998e8f-8491-454a-acd2-ec57054081fd.png">
     2.  
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/59086688/155272495-49ac45a4-3d34-44d0-9f59-ae7c93cf6daf.png">
      <When the data of trans_type = "POS" cannot be matched, there is a problem with the result display.>

**Comment by aceforeverd** [comment]
reproduced.

In convention, `max()` or `max_where` should 
- return NULL if there is no match or only NULL values in the input rows
- if NULL exists inside input rows, with other rows not NULL, NULL rows is omitted

```yaml
  - id: 5
    inputs:
      - name: t1
        columns: [ 'id bigint', 'uid string', 'mid string', 'cardno string', 'trans_time timestamp', 'trans_amt double', 'trans_type string', 'proving string', 'city string', 'label bool']
        indexs: [ 'idx:id:trans_time']
        rows:
          - [4, 'UserD', 'M4', '4444444', 20021114093726, 40.0, 'POST', 'NY', 'Newyork', true]
    sql: |
      select max_where(trans_amt, trans_type = 'POS') over w30d as max_trans from t1 window w30d as (partition by uid order by trans_time rows_range between 30d preceding and current row);
    expect:
      columns: ['max_trans double']
      rows:
        - ['0.0']
```
