### ISSUE TITLE
Wrong result when query on index

### ISSUE THREAD

**Issue by nautaa** [4paradigm/OpenMLDB#1356]
## Expected Behavior
correct result

## Current Behavior
If the order of conditions we specify in `where` is different from the order of the index, the result is wrong.
```
create table test(a string,b string,c string, index(key=(a,b)));
insert into test values('aaa','bbb','ccc');
```
```
select * from test where b='bbb' and a='aaa';
--- --- --- 
  a   b   c  
--- --- ---
```
```
select * from test where a='aaa' and b='bbb';
 ----- ----- ----- 
  a     b     c    
 ----- ----- ----- 
  aaa   bbb   ccc  
 ----- ----- -----
```

**Comment by lumianph** [comment]
this looks very weird, @jingchen2222 @aceforeverd  can you help check this?

**Comment by aceforeverd** [comment]
Will check

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-liguo](https://trello.com/c/Ut8UamBY/37-bugfix-liguo)

**Comment by aceforeverd** [comment]
confirmed, if the query order is different with the where condition order, result in empty list, e.g:
```yaml
    inputs:
      - columns: ["a string", "b string", "c string"]
        name: t1
        indexs: ["idx:b|a"]
        data: |
          aaa, bbb, ccc
    sql: |
      select * from t1 where a = 'aaa' and b = 'bbb'
    expect:
      columns: ["a string", "b string", "c string"]
      data: |
        aaa, bbb, ccc
```
