### ISSUE TITLE
window with union: ordering for union rows and original rows with the same order key is undefined

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1776]
**Bug Description**

in https://github.com/4paradigm/OpenMLDB/blob/361f44d433c2a7682a1ede4792afb8df4d1d5c74/hybridse/src/vm/runner.cc#L1530, union rows in rows filters out those with the same order key with current row, 

a correct case should be:
```yaml
- id: 66
    desc: 0s preceding
    inputs:
      - name: t1
        columns:
          - id int
          - ts timestamp
          - g int
        indexs:
          - idx:id:ts
        data: |
          1, 100, 111
      - name: t2
        columns:
          - ts timestamp
          - g int
          - val int
        indexs:
          - idx:g:ts
        data: |
          100, 111, 233
          100, 111, 17
          100, 111, 200
    # id, ts, g,   val
    # 1, 100, 111, 21
    # 1, 100, 111, 233
    sql: |
       select max(val) over w as mv
       from (select id, ts, g, 21 as val from t1)
       window w as(
       union (select 1 as id, ts, g, val from t2)
              partition by `g` order by `ts`
              rows_range between 1d preceding and 0s preceding EXCLUDE CURRENT_TIME INSTANCE_NOT_IN_WINDOW);
    expect:
      columns:
        - mv int
      order: mv
      data: |
        21
```

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
Solution:

should add classification for window union.

In an union window:
```sql
window w1 as (union (<union rows>) <window definition>)
```
- we call rows in `<window definition>` as `original rows`, and `union rows` for window union
- `union rows` may come from multiple datasource, e.g. `(UNION t2, t3 ...)`
- we say row A is before row B, means row A is more close to the `current row` from corresponding window

For Window Union:

- It is `UNION ALL`
- The order for window rows that have same row key/ts, among different datasource:
  - For original rows and other union rows, the original rows always appear before the union rows.
  - For union rows have multiple datasource, the order for union rows among datasource is **undefined**

Other notice:
- only apply to History Window, undefined for following window 
- SQL engine will explicitly force the order for union rows from different datasource, that is respect the order defined in SQL query. E.g in `(UNION t1, t2 ....)` , some ts rows in t1 always come before rows from t2. This may not true in offline mode. And you should not have any logic rely on this behavior.
- It may necessary to design another SQL option or a SQL system variable to control whether `original rows` should be before or after union rows

Example
```yaml
  - id: 18-1
    desc: |
      when UNION ROWS_RANGE has the same key with original rows, original rows first then union rows
    inputs:
      - name: t1
        columns:
          - id int
          - ts timestamp
          - g int
          - val int
        indexs:
          - idx:g:ts
        data: |
          1, 100, 111, 21
          2, 100, 111, 400
      - name: t2
        columns:
          - id int
          - ts timestamp
          - g int
          - val int
        indexs:
          - idx:g:ts
        data: |
          1,  99, 111, 233
          1, 100, 111, 200
          1, 101, 111, 17
    sql: |
       select
          id, count(val) over w as cnt,
          max(val) over w as mv,
          min(val) over w as mi,
          lag(val, 1) over w as l1
       from (select * from t1) window w as(
          union (select * from t2)
          partition by `g` order by `ts`
          rows_range between 1s preceding and 0s preceding);
    expect:
      columns:
        - id int
        - cnt int64
        - mv int
        - mi int
        - l1 int
      order: id
      data: |
        1, 3, 233, 21, 200
        2, 4, 400, 21, 21
  - id: 18-2
    desc: |
      when UNION ROWS has the same key with original rows, original rows first then union rows,
      union rows filtered out first for max window size limitation
    inputs:
      - name: t1
        columns:
          - id int
          - ts timestamp
          - g int
          - val int
        indexs:
          - idx:g:ts
        data: |
          1, 100, 111, 21
          2, 100, 111, 400
      - name: t2
        columns:
          - id int
          - ts timestamp
          - g int
          - val int
        indexs:
          - idx:g:ts
        data: |
          1,  88, 111, 999
          1,  99, 111, 233
          1, 100, 111, 200
          1, 101, 111, 17
    sql: |
       select
          id, count(val) over w as cnt,
          max(val) over w as mv,
          min(val) over w as mi,
          lag(val, 1) over w as l1
       from (select * from t1) window w as(
          union (select * from t2)
          partition by `g` order by `ts`
          ROWS BETWEEN 2 preceding and 0 preceding);
    expect:
      columns:
        - id int
        - cnt int64
        - mv int
        - mi int
        - l1 int
      order: id
      data: |
        1, 3, 233, 21, 200
        2, 3, 400, 21, 21
```
