### ISSUE TITLE
window `OPEN PRECEDING` in frame start border do not take effect

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1787]
**Bug Description**

```yaml
  - id: 19
    inputs:
      - name: t1
        columns:
          - id int
          - ts timestamp
          - g int
          - val int
        indexs:
          - idx:id:ts
        data: |
          1,  99, 111, 21
          2, 100, 111, 22
          3, 101, 111, 23
    sql: |
       select
          id, count(val) over w as cnt,
          max(val) over w as mv,
          min(val) over w as mi,
          lag(val, 1) over w as l1
       from t1 window w as(
          partition by `g` order by `ts`
          ROWS between 2 preceding and 0 OPEN PRECEDING);
    expect:
      columns:
        - id int
        - cnt int64
        - mv int
        - mi int
        - l1 int
      order: id
      data: |
         1, 0, NULL, NULL, NULL
         2, 1, 21, 21, 21
         3, 2, 22, 21, 22
```

the case do not pass because it still treat current row inside window when doing window aggregation. 
`OPEN PRECEDING` in end frame border seems work as expected though.

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.
