### ISSUE TITLE
OR和XOR运算符batch模式和request模式，计算结果不一致

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#187]
## Expected Behavior
两种模式的计算结果一致

## Current Behavior
两种模式的计算结果不一致

## Case
```
  - id: 0
    desc: "各种类型_逻辑运算_各种类型_正确"
    inputs:
      -
        columns : ["id bigint","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
        indexs: ["index1:id:c7"]
        rows:
          - [1,"aa",10,10,10,10.0,10.0,1590738989000,"2020-05-01",true]
          - [2,"aa",10,10,10,10.0,10.0,1590738989000,"2020-05-01",true]
      -
        columns : ["id bigint","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
        indexs: ["index1:id:c7"]
        rows:
          - [1,"bb",10,20,30,11.1,12.1,1590738989001,"2020-05-02",false]
          - [2,"",0,0,0,0.0,0.0,0,null,true]
    dataProvider:
      - ["AND","OR","XOR"]
      - ["{0}.c1","{0}.c2","{0}.c3","{0}.c4","{0}.c5","{0}.c6","{0}.c7","{0}.c8","{0}.c9"]
    sql: select d[1] d[0] {1}.c1 as b1,d[1] d[0] {1}.c2 as b2,d[1] d[0] {1}.c3 as b3,d[1] d[0] {1}.c4 as b4,d[1] d[0] {1}.c5 as b5,d[1] d[0] {1}.c6 as b6,d[1] d[0] {1}.c7 as b7,d[1] d[0] {1}.c8 as b8,d[1] d[0] {1}.c9 as b9 from {0} last join {1} ORDER BY {1}.c7 on {0}.id={1}.id;
    expect:
      columns: ["b1 bool","b2 bool","b3 bool","b4 bool","b5 bool","b6 bool","b7 bool","b8 bool","b9 bool"]
    expectProvider:
      0:
        rows:
          - [true,true,true,true,true,true,true,true,false]
          - [false,false,false,false,false,false,false,null,true]
      1:
        rows:
          - [true,true,true,true,true,true,true,true,false]
          - [false,false,false,false,false,false,false,null,true]
      2:
        rows:
          - [true,true,true,true,true,true,true,true,true]
          - [true,true,true,true,true,true,true,true,true]
      3:
        rows:
           - [true,true,true,true,true,true,true,true,true]
           - [true,true,true,true,true,true,true,true,true]
      4:
        rows:
           - [false,false,false,false,false,false,false,false,true]
           - [true,true,true,true,true,true,true,null,false]
```
