### ISSUE TITLE
Get incorrect result for min/max/count with null data which may be related to loop-combining codegen

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1927]
Now we may get incorrect result for methods of min/max/count with null data. Here is simple case which can be run in offline directly.

```
package com._4paradigm.openmldb.batchjob.tools.tobe.loaddata

import com._4paradigm.openmldb.batch.api.OpenmldbSession
import org.apache.spark.sql.{Row, SparkSession}
import org.apache.spark.sql.types.{IntegerType, StringType, StructField, StructType, TimestampType}
import java.sql.Timestamp

object SameWindowIssueLocal {

  def main(args: Array[String]): Unit = {

    val spark = SparkSession.builder().master("local")
      .getOrCreate()

    val sess = new OpenmldbSession(spark)

    val data = Seq(
      Row(1, "g1", Timestamp.valueOf("2021-02-01 13:59:58"), 1, -3),
      Row(2, "g1", Timestamp.valueOf("2021-02-01 13:59:59"), null, null),
      Row(3, "g1", Timestamp.valueOf("2021-02-01 14:00:00"), 2, -1),
      Row(4, "g2", Timestamp.valueOf("2021-02-01 14:00:00"), null, -1),
      Row(5, "g2", Timestamp.valueOf("2021-02-01 14:00:01"), null, -2),
      Row(6, "g3", Timestamp.valueOf("2021-02-01 13:54:02"), 1, 1),
    )
    val schema = StructType(List(
      StructField("row_id", IntegerType),
      StructField("key1", StringType),
      StructField("ts", TimestampType),
      StructField("l1", IntegerType),
      StructField("l2", IntegerType)
    ))
    val df = spark.createDataFrame(spark.sparkContext.makeRDD(data), schema)
    sess.registerTable("t1", df)

    val sqlText =
      """
        |select
        |    `row_id` as row_id_1,
        |    max(`l1`) over t6_2_key1_ts_0s_5s_10 as t6_2_l1_window_max_8,
        |    max(`l2`) over t6_2_key1_ts_0s_5s_10 as t6_2_l2_window_max_9
        |from
        |    `t1`
        |    window t6_2_key1_ts_0s_5s_10 as (partition by `key1` order by `ts` rows_range between 5s open preceding and 0s preceding MAXSIZE 10);
        |""".stripMargin

    val outputDf = sess.sql(sqlText)
    outputDf.show()

    val sqlText2 =
      """
        |select
        |    `row_id` as row_id_1,
        |    max(`l2`) over t6_2_key1_ts_0s_5s_10 as t6_2_l2_window_max_9
        |from
        |    `t1`
        |    window t6_2_key1_ts_0s_5s_10 as (partition by `key1` order by `ts` rows_range between 5s open preceding and 0s preceding MAXSIZE 10);
        |""".stripMargin

    val outputDf2 = sess.sql(sqlText2)
    outputDf2.show()
  }

}
``` 

If we only select the non-null column, the result is correct.

```
+--------+--------------------+
|row_id_1|t6_2_l2_window_max_9|
+--------+--------------------+
|       4|                  -1|
|       5|                  -1|
|       6|                   1|
|       1|                  -3|
|       2|                  -3|
|       3|                  -1|
+--------+--------------------+
```

If we select two columns and one of these columns has null data, the result is incorrect and make all result is null.

```
+--------+--------------------+--------------------+
|row_id_1|t6_2_l1_window_max_8|t6_2_l2_window_max_9|
+--------+--------------------+--------------------+
|       4|                null|                null|
|       5|                null|                null|
|       6|                   1|                   1|
|       1|                   1|                  -3|
|       2|                   1|                  -3|
|       3|                   2|                  -1|
+--------+--------------------+--------------------+
```

If we change the method from `max` to `add` which may not use loop-combining CodeGen, the result will be correct. So it may be the issue of handling null data in loop-combining CodeGen.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by aceforeverd** [comment]
re-produced online
```yaml
  - id: 101
    desc: codegen loop combine #todo
    inputs:
      - name: t1
        columns:
          - row_id int
          - key1 string
          - f1 float
          - f2 float
          - f3 float
          - d1 double
          - d2 double
          - d3 double
          - d4 double
          - l1 int64
          - l2 int64
          - i1 int
          - ts timestamp
        indexs:
          - idx:key1:ts
        data: |
          1, g1, 0.0, 0.0, 0.0,0.0,0.0,0.0,0.0, 1,    -3,   0, 1590738990000
          2, g1, 0.0, 0.0, 0.0,0.0,0.0,0.0,0.0, null, null, 0, 1590738990001
          3, g1, 0.0, 0.0, 0.0,0.0,0.0,0.0,0.0, 2,    -1,   0, 1590738990002
          4, g2, 0.0, 0.0, 0.0,0.0,0.0,0.0,0.0, null, -1,   0, 1590738990002
          5, g2, 0.0, 0.0, 0.0,0.0,0.0,0.0,0.0, null, -2,   0, 1590738990003
          6, g2, 0.0, 0.0, 0.0,0.0,0.0,0.0,0.0, 1,     1,   0, 1590738990004
    sql: |
      select
        `row_id`,
        key1,
        max(`f1`) over t6_2_key1_ts_0s_5s_10 as mf1,
        max(`f2`) over t6_2_key1_ts_0s_5s_10 as mf2,
        max(`f3`) over t6_2_key1_ts_0s_5s_10 as mf3,
        max(`d1`) over t6_2_key1_ts_0s_5s_10 as md1,
        max(`d2`) over t6_2_key1_ts_0s_5s_10 as md2,
        max(`d3`) over t6_2_key1_ts_0s_5s_10 as md3,
        max(`d4`) over t6_2_key1_ts_0s_5s_10 as md4,
        max(`l1`) over t6_2_key1_ts_0s_5s_10 as ml1,
        max(`l2`) over t6_2_key1_ts_0s_5s_10 as ml2,
        max(`i1`) over t6_2_key1_ts_0s_5s_10 as mi1
      from t1
          window t6_2_key1_ts_0s_5s_10 as (partition by `key1` order by `ts` rows_range between 5s open preceding and 0s preceding maxsize 10);
    expect:
      columns:
        - row_id int
        - key1 string
        - mf1 float
        - mf2 float
        - mf3 float
        - md1 double
        - md2 double
        - md3 double
        - md4 double
        - ml1 int64
        - ml2 int64
        - mi1 int
      order: row_id
      data: |
        1, g1, 0.0, 0.0,0.0,0.0,0.0,0.0,0.0, 1,    -3, 0
        2, g1, 0.0, 0.0,0.0,0.0,0.0,0.0,0.0, 1,    -3, 0
        3, g1, 0.0, 0.0,0.0,0.0,0.0,0.0,0.0, 2,    -1, 0
        4, g2, 0.0, 0.0,0.0,0.0,0.0,0.0,0.0, null, -1, 0
        5, g2, 0.0, 0.0,0.0,0.0,0.0,0.0,0.0, null, -1, 0
        6, g2, 0.0, 0.0,0.0,0.0,0.0,0.0,0.0, 1,     1, 0
```
