### ISSUE TITLE
ci: reuse the publish test reports workflow

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#2042]
**Describe the feature you'd like**

the cpp, hybridse and sdk test report actually follow the same logic but are written multiple times, like here:

- https://github.com/4paradigm/OpenMLDB/blob/3dfa6ceb0c2ca786258ef35afced9ed874a3131f/.github/workflows/hybridse-ci.yml#L88.

Idealy, they can avoid by reusing the same custom workflow, refer:

- https://docs.github.com/en/actions/using-workflows/reusing-workflows

There are six place where we can reusing

- in `cicd.yaml`, `hybridse-ci.yml` and `sdk.yml` for the `publish-test-reports` jobs
- and the three `publish-*-test-result-from-fork.yml`

**Additional context**

**Comment by mangoGoForward** [comment]
I want to tackle it, please assign to me

**Comment by lumianph** [comment]
> I want to tackle it, please assign to me

thanks~ I have assigned this task to you.

**Comment by mangoGoForward** [comment]
I had some problems when process on this issue. seems the workflow reused is a whole job, but our `publish-test-reports` jobs have a little difference, such as:
```
      - name: Publish Linux UT Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: linux-ut-result-*/**/*.xml
          check_name: Linux Test Report
          comment_title: Linux Test Report
```
in `cicd.yaml`, and 
```
      - name: Publish Linux UT Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: |
            linux-ut-result-*/**/*.xml
            mac-ut-result-*/**/*.xml
          check_name: SDK Test Report
          comment_title: SDK Test Report
```
in `sdk.yml`, the value of files is different. Also the `needs` is different in their own jobs
