### ISSUE TITLE
incorrect result `exclude current_row` If two windows are merged

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2211]
**Bug Description**
If two windows are merged, current_ Row will have problems.
+ case
```yaml
- id: 28
    desc: 两个窗口，一个rows，一个rows_range，current_row
    inputs:
      - columns: [ "c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date" ]
        indexs: [ "index1:c1:c7" ]
        rows:
          - [ "aa",20,30,1.1,2.1,1590738990000,"2020-05-01" ]
          - [ "aa",21,31,1.2,2.2,1590738991000,"2020-05-02" ]
          - [ "aa",22,32,1.3,2.3,1590738992000,"2020-05-03" ]
          - [ "aa",23,33,1.4,2.4,1590738993000,"2020-05-04" ]
          - [ "bb",24,34,1.5,2.5,1590738994000,"2020-05-05" ]
    sql: |
      SELECT c1, c3, sum(c4) OVER w1 as w1_c4_sum, count(c5) OVER w2 as w2_c5_count FROM {0} 
      WINDOW w1 AS (PARTITION BY {0}.c1 ORDER BY {0}.c7 ROWS BETWEEN 2 PRECEDING AND CURRENT ROW EXCLUDE CURRENT_ROW),
      w2 AS (PARTITION BY {0}.c1 ORDER BY {0}.c7 rows_range BETWEEN 2s PRECEDING AND CURRENT ROW EXCLUDE CURRENT_ROW);
    expect:
      order: c3
      columns: [ "c1 string","c3 int","w1_c4_sum bigint","w2_c5_count bigint" ]
      rows:
        - [ "aa",20,null,0 ]
        - [ "aa",21,30,1 ]
        - [ "aa",22,61,2 ]
        - [ "aa",23,63,2 ]
        - [ "bb",24,null,0 ]
```
**Expected Behavior**
![f93ba2bdf578ef11fdf41ff1fbdbd03b](https://user-images.githubusercontent.com/18275570/180119240-2f2cee91-7aa3-449f-b5c0-642ac7f75f35.png)
