### ISSUE TITLE
When ts=0, the calculation of history window is wrong

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2214]
**Bug Description**
When ts=0, the calculation of history window is wrong.
+ case
```yaml
  - id: 32
    desc: rows_range-纯历史窗口-current_row-ts=0
    inputs:
      - columns: [ "c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date" ]
        indexs: [ "index1:c1:c7" ]
        rows:
          - [ "aa",20,30,1.1,2.1,0,"2020-05-01" ]
          - [ "aa",21,31,1.2,2.2,0,"2020-05-02" ]
          - [ "aa",22,32,1.3,2.3,1000,"2020-05-03" ]
          - [ "aa",23,33,1.4,2.4,2000,"2020-05-04" ]
          - [ "bb",24,34,1.5,2.5,1590738994000,"2020-05-05" ]
    sql: |
      SELECT c1, c3, sum(c4) OVER w1 as w1_c4_sum FROM {0} WINDOW w1 AS (PARTITION BY {0}.c1 ORDER BY {0}.c7 ROWS_RANGE BETWEEN 2s PRECEDING AND 1s PRECEDING EXCLUDE CURRENT_ROW);
    expect:
      order: c3
      columns: [ "c1 string","c3 int","w1_c4_sum bigint" ]
      rows:
        - [ "aa",20,null ]
        - [ "aa",21,null ]
        - [ "aa",22,61 ]
        - [ "aa",23,93 ]
        - [ "bb",24,null ]
```

**Expected Behavior**
![image](https://user-images.githubusercontent.com/18275570/180157948-153e5b2f-bcfa-42a4-b815-ce4d7b645d18.png)

**Relation Case**
test_current_row.yaml id:32

**Steps to Reproduce**

1. 
2. 
3. 
4.
