### ISSUE TITLE
When the disk table is in the request mode, duplicate data (key and TS are the same) cannot be overwritten

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2245]
**Bug Description**
When the disk table is in the request mode, duplicate data (key and TS are the same) cannot be overwritten

+ case
```yaml
  - id: 12
    desc: SSD 插入索引和ts 一样的数据
    inputs:
      -
        columns : ["c1 string","c2 int","c3 bigint","c4 timestamp"]
        indexs: ["index1:c1:c4"]
        storage: SSD
        rows:
          - ["aa", 2, 3, 1590738989000]
          - ["aa", 2, 3, 1590738989000]
          - ["aa", 2, 3, 1590738989000]
    sql: select * from {0};
    expect:
      columns: ["c1 string","c2 int","c3 bigint","c4 timestamp"]
      rows:
        - ["aa", 2, 3, 1590738989000]
```
![image](https://user-images.githubusercontent.com/18275570/180993462-1daf5fc3-6db1-4ecf-8c17-2aa0069809cd.png)

**Expected Behavior**

```yaml
    expect:
      columns: ["c1 string","c2 int","c3 bigint","c4 timestamp"]
      rows:
        - ["aa", 2, 3, 1590738989000]
```

**Steps to Reproduce**

1. 
2. 
3. 
4.
