### ISSUE TITLE
The disk table is in request mode, and the data is expired

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2246]
**Bug Description**
The disk table is in request mode, and the data is expired
+ case
```yaml
  - id: 15
    desc: 创建磁盘表，ttl_type=latest,ttl=4,insert 10
    inputs:
      -
        columns : ["c1 string","c2 int","c3 bigint","c4 timestamp"]
        indexs: ["index1:c1:c4:4:latest"]
        storage: SSD
        rows:
          - ["bb", 2, 3, 1590738989000]
          - ["bb", 4, 5, 1590738990000]
          - ["bb", 6, 7, 1590738991000]
          - ["bb", 8, 9, 1590738992000]
          - ["bb", 10, 11, 1590738993000]
          - ["bb", 12, 13, 1590738994000]
          - ["bb", 14, 15, 1590738995000]
          - ["bb", 16, 17, 1590738996000]
          - ["bb", 18, 19, 1590738997000]
          - ["bb", 20, 21, 1590738998000]
    sql: select c1,c2,c3 from {0};
    expect:
      columns: ["c1 string","c2 int","c3 bigint"]
      rows:
        - ["bb", 20, 21]
        - ["bb", 18, 19]
        - ["bb", 16, 17]
        - ["bb", 14, 15]
```
![image](https://user-images.githubusercontent.com/18275570/180994764-eafada3a-eb8f-40c4-9957-a3cc91d4e4b6.png)

**Expected Behavior**
```yaml
    expect:
      columns: ["c1 string","c2 int","c3 bigint"]
      rows:
        - ["bb", 20, 21]
        - ["bb", 18, 19]
        - ["bb", 16, 17]
        - ["bb", 14, 15]
```

**Steps to Reproduce**

1. 
2. 
3. 
4.
