### ISSUE TITLE
When the table has two indexes, delete the other index, and the result is wrong

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2271]
**Bug Description**
When the table has two indexes, delete the other index, and the result is wrong.
+ case
```yaml
  -
    id: 4
    desc: 两个索引 delete 其中一个
    inputs:
      -
        columns: ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
        indexs: ["index1:c1:c7","index2:c2:c7"]
        rows:
          - [1,"aa",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
          - [2,"bb",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
          - [3,"aa",1,2,3,1.1,2.1,1590738990000,"2020-05-01",true]
          - [4,"aa",2,2,3,1.1,2.1,1590738991000,"2020-05-01",true]
    sqls:
      - delete from {0} where c2=2;
      - select * from {0};
    expect:
      columns: ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
      order: id
      rows:
        - [1,"aa",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
        - [2,"bb",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
        - [3,"aa",1,2,3,1.1,2.1,1590738990000,"2020-05-01",true]
```

**Expected Behavior**

**Steps to Reproduce**

1.  create table
```sql
create table auto_tKWhpiej(
id int,
c1 string,
c2 smallint,
c3 int,
c4 bigint,
c5 float,
c6 double,
c7 timestamp,
c8 date,
c9 bool,
index(key=(c1),ts=c7),
index(key=(c2),ts=c7))options(partitionnum=1,replicanum=1);
```
2.  insert
```sql
insert into auto_tKWhpiej values
(1,'aa',1,2,3,1.1,2.1,1590738989000,'2020-05-01',true)
insert into auto_tKWhpiej values
(2,'bb',1,2,3,1.1,2.1,1590738989000,'2020-05-01',true)
insert into auto_tKWhpiej values
(3,'aa',1,2,3,1.1,2.1,1590738990000,'2020-05-01',true)
insert into auto_tKWhpiej values
(4,'aa',2,2,3,1.1,2.1,1590738991000,'2020-05-01',true);
```
3.  delete
```sql
delete from auto_tKWhpiej where c2=2;
```
4.  select
```sql
select * from auto_tKWhpiej;
```
