### ISSUE TITLE
Delete the empty string, and the result is wrong

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2274]
**Bug Description**
Delete the empty string, and the result is wrong
+ case
```yaml
  -
    id: 8
    desc: delete 空串
    inputs:
      -
        columns: ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
          - [2,"bb",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
          - [3,"",1,2,3,1.1,2.1,1590738990000,"2020-05-01",true]
    sqls:
      - delete from {0} where c1='';
      - select * from {0};
    expect:
      columns: ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
      rows:
        - [2,"bb",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
```
actual result:
![image](https://user-images.githubusercontent.com/18275570/181864798-92320a40-b655-46ea-a605-d30ece0adf98.png)

**Expected Behavior**
It can be deleted successfully and the result is correct

**Steps to Reproduce**
1.  
```sql
create table auto_NWMGBsli(
id int,
c1 string,
c2 smallint,
c3 int,
c4 bigint,
c5 float,
c6 double,
c7 timestamp,
c8 date,
c9 bool,
index(key=(c1),ts=c7))options(partitionnum=1,replicanum=1);
```
2.  
```sql
insert into auto_NWMGBsli values
(1,'',1,2,3,1.1,2.1,1590738989000,'2020-05-01',true);
insert into auto_NWMGBsli values
(2,'bb',1,2,3,1.1,2.1,1590738989000,'2020-05-01',true);
insert into auto_NWMGBsli values
(3,'',1,2,3,1.1,2.1,1590738990000,'2020-05-01',true);
```
3.  
```sql
delete from auto_NWMGBsli where c1='';
```
4.  
```sql
select * from auto_NWMGBsli;
```

**Comment by wuyou10206** [comment]
Delete date type, the result is wrong.
```yaml
  -
    id: 13
    desc: delete date
    inputs:
      -
        columns: ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
        indexs: ["index1:c8:c7"]
        rows:
          - [1,"aa",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
          - [2,"bb",1,2,3,1.1,2.1,1590738989000,"2020-05-02",true]
          - [3,"aa",1,2,3,1.1,2.1,1590738990000,"2020-05-01",true]
    sqls:
      - delete from {0} where c8='2020-05-02';
      - select * from {0};
    expect:
      columns: ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
      order: id
      rows:
        - [1,"aa",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
        - [3,"aa",1,2,3,1.1,2.1,1590738990000,"2020-05-01",true]
```

**Comment by wuyou10206** [comment]
Delete boolean type, the result is wrong
```yaml
    id: 15
    desc: delete bool
    inputs:
      -
        columns: ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
        indexs: ["index1:c9:c7"]
        rows:
          - [1,"aa",1,2,3,1.1,2.1,1590738989000,"2020-05-01",false]
          - [2,"bb",1,2,3,1.1,2.1,1590738989000,"2020-05-01",true]
          - [3,"aa",1,2,3,1.1,2.1,1590738990000,"2020-05-01",true]
    sqls:
      - delete from {0} where c9=true;
      - select * from {0};
    expect:
      columns: ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
      rows:
        - [1,"aa",1,2,3,1.1,2.1,1590738989000,"2020-05-01",false]
```
