### ISSUE TITLE
long window:count_where the second parameter of where. If it is of date type, an error message should be prompted

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2314]
**Bug Description**
count_ where The second parameter of where. If it is of date type, an error message should be prompted.
Now it does not prompt an error message, but the result is wrong.

+ case
```yaml
  -
    id: 27
    desc: 长窗口count_where，第二个参数类型是date
    longWindow: w1:2
    inputs:
      -
        columns : ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
        index: ["index1:c1:c7:0:latest"]
        rows:
          - [1,"aa",1,20,30,1.1,2.1,1590738990000,"2020-05-01",true]
          - [2,"aa",2,21,31,1.2,2.2,1590738990001,"2020-05-02",true]
          - [3,"aa",3,22,32,1.3,2.3,1590738990002,"2020-05-03",true]
          - [4,"aa",4,23,33,1.4,2.4,1590738990003,"2020-05-04",true]
          - [5,"aa",5,24,34,1.5,2.5,1590738990004,"2020-05-05",false]
    sql: |
      SELECT id, c1, count_where(c8,c8<"2020-05-04") OVER w1 as w1_count FROM {0} WINDOW w1 AS (PARTITION BY {0}.c1 ORDER BY {0}.c7 ROWS BETWEEN 2 PRECEDING AND CURRENT ROW);
    expect:
      order: id
      columns: ["id int","c1 string","w1_count bigint"]
      rows:
        - [1,"aa",1]
        - [2,"aa",2]
        - [3,"aa",3]
        - [4,"aa",2]
        - [5,"aa",1]
```
![b872458122f95d57444e8e56ff5c6e7f](https://user-images.githubusercontent.com/18275570/183328506-fddca461-f192-4836-a920-cf6dbbd59dfc.png)

**Expected Behavior**
Error message expected

**Steps to Reproduce**

1. 
2. 
3. 
4.
