### ISSUE TITLE
cicd: build on push events to default branch. release on tag push, upload artifacts on other commit push

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#233]
**Is your feature request related to a problem? Please describe.**
extra steps on commit pushed to default branch
1. tag push: trigger a release build, with release note and asserts. 
   - tag may not at main, SemVer tag only
2. commit push to main: trigger a normal build, but upload build outputs as GitHub artifacts

**Describe the solution you'd like**
cicd
**Describe alternatives you've considered**
Nop
**Additional context**
Nop

TODO

- [x] auto release on tag push
- [ ] get release note from `CHANGELOG.md`
- [ ] 匹配代码中的 version
- [ ] upload asserts
  - [x]  linux archive
  - [x] mac archive, require 4paradigm/HybridSE#47 
  - [ ] digest
  - [ ] digest.asc
- [x] upload artifacts on commit push
  - note: artifacts take up space quota for private repo

**Comment by aceforeverd** [comment]
will use [action-gh-release](https://github.com/softprops/action-gh-release).

Upload release asserts. Meanwhile, consider add a `CHANGLOG.md` file so we can parse Release Note from that file.

**Comment by aceforeverd** [comment]
Also, for every commit pushed to main, run [upload-artifacts](https://github.com/actions/upload-artifact) action.

**Comment by aceforeverd** [comment]
we can use actions/upload-artifact and action/download-artifact 
when this is open and docker image upgrade to cenos:7
```yaml
  release:
    runs-on: self-hosted
    needs: build
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Get Artifacts
        run: |
          echo Get Artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            hybridse-*.tar.gz
```
