### ISSUE TITLE
long window: count (bool) prompt error message

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2339]
**Bug Description**
long window: count (bool) prompt error message
+ case
```yaml
  -
    id: 7
    desc: 长窗口count/avg/sum/max/min，bool类型
    longWindow: w1:2s
    tags: ["TODO","count(bool)有问题，bug，修复后验证"]
    inputs:
      -
        columns : ["id int","c1 string","c2 smallint","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date","c9 bool"]
        index: ["index1:c1:c7"]
        rows:
          - [1,"aa",1,20,30,1.1,2.1,1590738990000,"2020-05-01",true]
          - [2,"aa",2,21,31,1.2,2.2,1590738991000,"2020-05-02",true]
          - [3,"aa",3,22,32,1.3,2.3,1590738992000,"2020-05-03",true]
          - [4,"aa",4,23,33,1.4,2.4,1590738993000,"2020-05-04",true]
          - [5,"aa",5,24,34,1.5,2.5,1590738994000,"2020-05-05",false]
    sql: |
      SELECT id, c1, d[0](c9,c2<4) OVER w1 as w1_udaf FROM {0} WINDOW w1 AS (PARTITION BY {0}.c1 ORDER BY {0}.c7 ROWS_RANGE BETWEEN 2s PRECEDING AND CURRENT ROW);
    dataProvider:
      - ["min","max","sum","avg","count"]
    expectProvider:
      0:
        success: false
        msg: fail
      1:
        success: false
        msg: fail
      2:
        success: false
        msg: fail
      3:
        success: false
        msg: fail
      4:
        order: id
        columns: ["id int","c1 string","w1_udaf bigint"]
        rows:
          - [1,"aa",1]
          - [2,"aa",2]
          - [3,"aa",3]
          - [4,"aa",3]
          - [5,"aa",3]
```
+ log
![image](https://user-images.githubusercontent.com/18275570/184080128-2f2c1c68-1c60-47d0-8c5f-185e47145c3a.png)

**Expected Behavior**
Boolean types are supported

**Steps to Reproduce**

1. 
2. 
3. 
4.
