### ISSUE TITLE
where xxx = xxx limit 1返回多条数据

### ISSUE THREAD

**Issue by uttinie** [4paradigm/OpenMLDB#2433]
**Bug Description**

![image](https://user-images.githubusercontent.com/18255088/188360593-317ab962-83d6-4702-9a29-290bd8efdb3d.png)

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
thanks, reproduced with simple yaml
```yaml
  - id: 237
    inputs:
      - name: actions
        columns:
          - userId string
          - itemId int
          - actionTime timestamp
        indexs:
          - index2:itemId:actionTime
        data: |
          a, 1, 1000
          a, 2, 2000
          b, 3, 3000
          b, 3, 3000

    sql: |
      select * from actions where itemId != 3 limit 1
    expect:
      order: itemId
      columns:
        - userId string
        - itemId int
        - actionTime timestamp
      data: |
        a, 1, 1000
```
