### ISSUE TITLE
Empty window data for ROWS WINDOW with `UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT_ROW`

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#2597]
> id   uid     mid   cardno    trans_time      trans_amt    trans_type   province   city       label  
>  ---- ------- ----- --------- --------------- ------------ ------------ ---------- ---------- ------- 
>   7    UserB   M2    2222222   1644206400000   30.000000    POS          SH         ShangHai   true   
>   9    UserA   M3    1111111   1644292800000   100.000000   POS          BJ         BeiJing    true   
>   2    UserB   M3    2222222   1643686200000   10.000000    POS          SH         ShangHai   true   
>   3    UserA   M2    1111111   1643857200000   20.000000    POS          SH         ShangHai   true   
>   4    UserA   M3    1111111   1644202800000   15.000000    POS          SH         ShangHai   true   
>   10   UserB   M5    2222222   1644289200000   10.000000    POS          SH         ShangHai   true   
>   5    UserB   M1    2222222   1644199200000   20.000000    POS          SH         ShangHai   true   
>   1    UserA   M1    1111111   1643767200000   10.000000    CASH         SH         ShangHai   true   
>   8    UserA   M2    1111111   1644289200000   50.000000    CASH         BJ         BeiJing    true   
>   6    UserA   M1    1111111   1644210000000   20.000000    CASH         BJ         BeiJing    true   
>  ---- ------- ----- --------- --------------- ------------ ------------ ---------- ---------- -------

Thanks confirmed. Using `UNBOUNDED PRECEDING` with `CURRENT ROW EXCLUDE CURRENT_ROW` cause the problem. 
A const start frame like `4 PRECEDING` is correct. 

I will tracking it in a new issue

A reproducable yaml
```yaml
  - id: 8
    desc: |
      ROWS window with end frame 'CURRENT_ROW', exclude current_row
    inputs:
      - name: t1
        columns:
          - id int
          - ts timestamp
          - g int
          - val int
        indexs:
          - idx:g:ts
        data: |
          1,  99000, 111, 21
          2, 100000, 111, 22
          3, 101000, 111, 23
          4, 102000, 111, 44
          5, 100000, 114, 56
          6, 102000, 114, 52
    sql: |
       select
          id,
          count(val) over w as cnt,
          max(val) over w as mv,
          min(val) over w as mi,
          lag(val, 1) over w as l1
       FROM t1 WINDOW w as(
          PARTITION by `g` ORDER by `ts`
          ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT_ROW);
    expect:
      columns:
        - id int
        - cnt int64
        - mv int
        - mi int
        - l1 int
      order: id
      data: |
         1, 0, NULL, NULL, NULL
         2, 1, 21, 21, 21
         3, 2, 22, 21, 22
         4, 3, 23, 21, 23
         5, 0, NULL, NULL, NULL
         6, 1, 56, 56, 56

```

_Originally posted by @aceforeverd in https://github.com/4paradigm/OpenMLDB/issues/2574#issuecomment-1262038623_
