### ISSUE TITLE
DistributedIterator mess up the key if there are multiple indexes

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#2629]
**Bug Description**

sql case:
```yaml
  -
    id: 3
    desc: 3 window,pk不同
    inputs:
      -
        columns : ["id int","c1 string", "c2 string", "c3 int","c4 bigint","c7 timestamp"]
        indexs: ["index1:c1:c7", "index2:c2:c7", "index3:c3:c7"]
        rows:
          - [1,"aa", "1", 20,30,1590738990000]
          - [2,"aa", "2", 20,31,1590738991000]
          - [3,"bb", "1", 20,32,1590738992000]
          - [4,"bb", "2", 20,33,1590738993000]
          - [5,"cc", "1", 21,34,1590738994000]
          - [6,"aa", "1", 21,35,1590738995000]
          - [7,"aa", "1", 21,36,1590738996000]
    sql: |
      SELECT id, c1, c2, c3,
      count(id) OVER w1 as w1_count,
      count(id) OVER w2 as w2_count,
      sum(c4) OVER w3 as w3_c4_sum
      FROM {0} WINDOW
      w1 AS (PARTITION BY c1 ORDER BY c7 ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),
      w2 AS (PARTITION BY c2 ORDER BY c7 ROWS BETWEEN 3 PRECEDING AND CURRENT ROW),
      w3 AS (PARTITION BY c3 ORDER BY c7 ROWS BETWEEN 2 PRECEDING AND CURRENT ROW);
    expect:
      order: id
      columns: ["id int","c1 string", "c2 string", "c3 int","w1_count bigint","w2_count bigint", "w3_c4_sum bigint"]
      rows:
        - [1,"aa", "1", 20, 1, 1, 30]
        - [2,"aa", "2", 20, 2, 1, 61]
        - [3,"bb", "1", 20, 1, 2, 93]
        - [4,"bb", "2", 20, 2, 2, 96]
        - [5,"cc", "1", 21, 1, 3, 34]
        - [6,"aa", "1", 21, 3, 4, 69]
        - [7,"aa", "1", 21, 3, 4, 105]
```

Got unexpected result:
```
- [3, "bb", "1", 20, 1, 2, 93]
- [4, "bb", "2", 20, 2, 2, 96]
- [1, "aa", "1", 20, 1, 1, 30]
- [2, "aa", "2", 20, 2, 1, 61]
```

By turning on the debug, we see the `TabletPartition` output is:
![image](https://user-images.githubusercontent.com/7508922/194851348-fcfdfb93-4f1e-4498-9b48-4277e9a9c0c8.png)
