### ISSUE TITLE
There is no data in the result of full table aggregation calculation for an empty table

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2667]
**Bug Description**
There is no data in the result of full table aggregation calculation for an empty table
![image](https://user-images.githubusercontent.com/18275570/196114883-86d9e911-97bc-43d3-b9be-1510af4da0e2.png)

+ case
```yaml
  - id: 3
    desc: "表是空的"
    tags: ["TODO","@chengjing,bug,"]
    mode: request-unsupport
    inputs:
      -
        columns : ["id bigint","c1 string","c2 int","c7 timestamp"]
        indexs: ["index1:c1:c7"]
    sql: select count(c2) as v1,max(c2) as v2,min(c2) as v3,avg(c2) as v4,sum(c2) as v5 from {0};
    expect:
      order: c1
      columns: ["v1 int","v2 int","v3 int","v4 double","v5 int"]
      rows:
        - [0,null,null,null,null]
```

**Expected Behavior**
Expect to have data
**Relation Case**
test_udaf_table.yaml  id:3
**Steps to Reproduce**

1. 
2. 
3. 
4.
