### ISSUE TITLE
SQL expression: support the `list_at` or `array_at` semantic

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#3023]
after e.g `split_by_value`, user may want to access the nth value of the output list

**Comment by aceforeverd** [comment]
note `at(split('a,b', ','), 1)` possibly break due to past changes

**Comment by aceforeverd** [comment]
> note `at(split('a,b', ','), 1)` possibly break due to past changes

`at` is runable as: 
```yaml
  - id: 108
    desc: date predicates
    inputs:
      - name: t1
        columns: ["id int32", "b int32", "ts int64", "val int"]
        indexs: ["idx1:id:ts", "idx2:b:ts"]
        data: |
          1, 10, 1000, 9
          2, 10, 1001, 10
    sql: |
      select at(split_by_value(top_n_value_max_cate_where(val, true, b, 1) over w, ',', ':'), 0) as out from t1
      window w as (
        partition by b order by ts
        rows between unbounded preceding and current row
      )
```

However, semantic of `at` is not clear currently.
- `at` is mainly (at least currently) used as window functions, not non-window row project
- semantic of list type of udf system is not clear too, see #3099 
- `at` is synonym to `lag` currently, to archive the required list_at semantic for `at`, this synonym semantic must removed.
