### ISSUE TITLE
can't lift child `i` to list for udf functions which requires params as list

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#3039]
some udf function requires list param, e.g `lag`, `first_value`, `join`, while some exprs can't infer to list, e.g `case when` expr. 

A yaml case:

```yaml
  - id: 22
    inputs:
      - name: t1
        columns: ["id string", "gp int", "ts int64", "val int"]
        indexs: ["index1:gp:ts"]
        rows:
          - ["0", 1, 5, 66]
          - ["1", 1, 6, 67]
    sql: |
      select id,
      lag(case when ts < 10 then ts else null end, 1) over w as agg
      from t1
      WINDOW w AS (PARTITION BY gp ORDER BY ts ROWS_RANGE BETWEEN 60d PRECEDING AND CURRENT ROW MAXSIZE 101)
    expect:
      success: true
```
