### ISSUE TITLE
Update the doc of FeatInsight example config file

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#3770]
**Bug Description**

Update the doc in https://openmldb.ai/docs/zh/main/app_ecosystem/feat_insight/install/package.html .

```
server:
  port: 8888
 
openmldb:
  zk_cluster: 127.0.0.1:2181
  zk_path: /openmldb
  apiserver: 127.0.0.1:9080
```

Change to the following config.

```
server:
  port: 8888

openmldb:
  zk_cluster: openmldb-zk:2181
  zk_path: /openmldb
  apiserver: openmldb-zk:9080
  skip_index_check: false

mockuser:
  username: root
  password: root
```
