### ISSUE TITLE
Fail to query over tables with the same table_name and different db name.

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#572]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

Error when try to join tables from two databases with the same table names.
```yaml
  - id: 5
    desc: Last Join tables from two databases with same table_name - default db is db, explicit db1 and db2
    db: db
    inputs:
      - db: db1
        columns: [ "c1 string","c2 int","c3 bigint","c4 timestamp" ]
        indexs: [ "index1:c1:c4" ]
        name: t1
        rows:
          - [ "aa",2,3,1590738989000 ]
          - [ "bb",21,31,1590738990000 ]
          - [ "cc",41,51,1590738991000 ]
      - db: db2
        columns: [ "c1 string","c2 int","c3 bigint","c4 timestamp" ]
        indexs: [ "index1:c1:c3" ]
        name: t1
        rows:
          - [ "aa",2,13,1590738989000 ]
          - [ "bb",21,131,1590738990000 ]
          - [ "cc",41,151,1590738992000 ]
    sql: select db1.{0}.c1, db1.{0}.c2,db2.{1}.c3,db2.{1}.c4 from db1.{0} last join db2.{1} ORDER BY db2.{1}.c3 on db1.{0}.c1=db2.{1}.c1;
    expect:
      order: c1
      columns: [ "c1 string","c2 int","c3 bigint","c4 timestamp" ]
      rows:
        - [ "aa",2,13,1590738989000 ]
        - [ "bb",21,131,1590738990000 ]
        - [ "cc",41,151,1590738992000 ]
```
## Expected Behavior

Join success
## Current Behavior

SQL Compile error.
## Possible Solution

Something goes wrong with the SQL compiler.

## Steps to Reproduce

1. 
2.
3.
4.
