### ISSUE TITLE
Lastjoin Miss index execution failed when performance is not sensitive

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#612]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion
## Expected Behavior
execute success

## Current Behavior
fail to query tablet

## Steps to Reproduce
1. create t1:
create table auto_jGgwTodj(
c1 string,
c2 int,
c3 bigint,
c4 timestamp,
index(key=(c1),ts=c4))options(partitionnum=1,replicanum=1);
2. create t2
create table auto_JBbInAcR(
c1 string,
c2 int,
c3 bigint,
c4 timestamp,
index(key=(c2),ts=c4))options(partitionnum=1,replicanum=1);
3.insert
insert into auto_jGgwTodj values('aa',2,3,1590738989000);
insert into auto_jGgwTodj values('bb',21,31,1590738990000);

insert into auto_JBbInAcR values('aa',2,13,1590738989000);
insert into auto_JBbInAcR values('bb',21,131,1590738990000);
insert into auto_JBbInAcR values('cc',41,121,1590738991000);
4. set performance_sensitive
set performance_sensitive=false;
5. select
select auto_jGgwTodj.c1,auto_jGgwTodj.c2,auto_JBbInAcR.c3,auto_JBbInAcR.c4 from auto_jGgwTodj last join auto_JBbInAcR order by auto_JBbInAcR.c4 on auto_jGgwTodj.c1=auto_JBbInAcR.c1;

## Case
```yaml
  - id: 4-6
    desc: lastjoin-拼表条件没有命中索引
    inputs:
      - columns: [ "c1 string","c2 int","c3 bigint","c4 timestamp" ]
        indexs: [ "index1:c1:c4" ]
        rows:
          - [ "aa",2,3,1590738989000 ]
          - [ "bb",21,31,1590738990000 ]
      - columns: [ "c1 string","c2 int","c3 bigint","c4 timestamp" ]
        indexs: [ "index1:c2:c4" ]
        rows:
          - [ "aa",2,13,1590738989000 ]
          - [ "bb",21,131,1590738990000 ]
          - [ "cc",41,121,1590738991000 ]
    sql: select {0}.c1,{0}.c2,{1}.c3,{1}.c4 from {0} last join {1} order by {1}.c4 on {0}.c1={1}.c1;
    expect:
      columns: [ "c1 string", "c2 int", "c3 bigint", "c4 timestamp" ]
      rows:
        - [ "aa", 2, 13, 1590738989000 ]
        - [ "bb", 21, 131, 1590738990000 ]
```
