### ISSUE TITLE
window partition by Miss index execution result error when performance is not sensitive

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#613]
partition by float or double result error,but  partition by int is right
## Expected Behavior
 ---- ---- ---------- -----------
  id   c1   c5         w1_c4_sum
 ---- ---- ---------- -----------
  1    aa   1.100000   30
  2    bb   1.100000   61
  3    cc   1.100000   93
  4    dd   1.100000   96
  5    ee   1.200000   34
 ---- ---- ---------- -----------
## Current Behavior
 ---- ---- ---------- -----------
  id   c1   c5         w1_c4_sum
 ---- ---- ---------- -----------
  1    aa   1.100000   30
  2    bb   1.100000   61
  3    cc   1.100000   93
  4    dd   1.100000   96
  5    ee   1.200000   99
 ---- ---- ---------- -----------

## Steps to Reproduce
1. create
create table auto_LfLMDwcY(
id int,
c1 string,
c3 int,
c4 bigint,
c5 float,
c6 double,
c7 timestamp,
c8 date,
index(key=(c1),ts=c7))options(partitionnum=1,replicanum=1);
2. insert
insert into auto_LfLMDwcY values(1,'aa',20,30,1.1,2.1,1590738990000,'2020-05-01');
insert into auto_LfLMDwcY values(2,'bb',20,31,1.1,2.2,1590738991000,'2020-05-02');
insert into auto_LfLMDwcY values(3,'cc',20,32,1.1,2.3,1590738992000,'2020-05-03');
insert into auto_LfLMDwcY values(4,'dd',20,33,1.1,2.4,1590738993000,'2020-05-04');
insert into auto_LfLMDwcY values(5,'ee',21,34,1.2,2.5,1590738994000,'2020-05-05');
3. set performance_sensitive
set performance_sensitive=false;
4. select
SELECT id, c1, c5, sum(c4) OVER w1 as w1_c4_sum FROM auto_LfLMDwcY WINDOW w1 AS (PARTITION BY auto_LfLMDwcY.c5 ORDER BY auto_LfLMDwcY.c7 ROWS_RANGE BETWEEN 2s PRECEDING AND CURRENT ROW);

## case
```yaml
  - id: 2
    desc: rows_range-float为partition by-未命中索引
    inputs:
      - columns: [ "id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date" ]
        indexs: [ "index1:c1:c7" ]
        rows:
          - [ 1,"aa",20,30,1.1,2.1,1590738990000,"2020-05-01" ]
          - [ 2,"bb",20,31,1.1,2.2,1590738991000,"2020-05-02" ]
          - [ 3,"cc",20,32,1.1,2.3,1590738992000,"2020-05-03" ]
          - [ 4,"dd",20,33,1.1,2.4,1590738993000,"2020-05-04" ]
          - [ 5,"ee",21,34,1.2,2.5,1590738994000,"2020-05-05" ]
    sql: |
      SELECT id, c1, c5, sum(c4) OVER w1 as w1_c4_sum FROM {0} WINDOW w1 AS (PARTITION BY {0}.c5 ORDER BY {0}.c7 ROWS_RANGE BETWEEN 2s PRECEDING AND CURRENT ROW);
    expect:
      order: id
      columns: [ "id int","c1 string","c5 float","w1_c4_sum bigint" ]
      rows:
        - [ 1,"aa",1.1,30 ]
        - [ 2,"bb",1.1,61 ]
        - [ 3,"cc",1.1,93 ]
        - [ 4,"dd",1.1,96 ]
        - [ 5,"ee",1.2,34 ]
```

**Comment by aceforeverd** [comment]
https://github.com/4paradigm/OpenMLDB/blob/1b83bfc2763e7d5b1e0f2950263c17a0b3ca0ea2/hybridse/src/vm/runner.cc#L3158 
generated key is the same empty string for float type (not handled)

**Comment by jingchen2222** [comment]
> https://github.com/4paradigm/OpenMLDB/blob/1b83bfc2763e7d5b1e0f2950263c17a0b3ca0ea2/hybridse/src/vm/runner.cc#L3158
> 
> 
> generated key is the same empty string for float type (not handled)

Yes, so we have to assert partition key's type when compiling sql.

**Comment by aceforeverd** [comment]
> https://github.com/4paradigm/OpenMLDB/blob/1b83bfc2763e7d5b1e0f2950263c17a0b3ca0ea2/hybridse/src/vm/runner.cc#L3158
> 
> 
> generated key is the same empty string for float type (not handled)

And to notice, the same problem applied to `GROUP` and `LAST JOIN` operation, whose runner calling flow also involve `Partition`. 

Here are example test case:
- Group

   ```yaml
  - id: 3
    desc: group by 12
    inputs:
      - columns: [ "id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date" ]
        indexs: [ "index1:c1:c7" ]
        rows:
          #   id, c1    c3, c4,   c5,   c6,  c7,            c8
          - [ 1, "aa",  20,  30,  1.1,  2.1, 1590738990000, "2020-05-01" ]
          - [ 2, "bb",  20,  31,  1.1,  2.2, 1590738991000, "2020-05-02" ]
          - [ 3, "cc",  20,  32,  1.1,  2.3, 1590738992000, "2020-05-03" ]
          - [ 4, "dd",  20,  33,  1.1,  2.4, 1590738993000, "2020-05-04" ]
          - [ 5, "ee",  21,  34,  1.2,  2.5, 1590738994000, "2020-05-05" ]
    sql: |
      select c5, sum(c4) as s4 from {0} group by c5;
   ```

- last join
   ```yaml
  - id: 4
    desc: last join Filter key is not in supported type
    sql: |
      SELECT t1.col1 as id, t1.col0 as t1_col0, t1.col1 + t2.col1 + 1 as test_col1, t1.col2 as t1_col2, str1 FROM t1
      last join t2 order by t2.col5 on t1.col4 = t2.col4 AND t1.col5 = t2.col5;
    inputs:
      - name: t1
        columns: ["col0:string", "col1:int32", "col2:int16", "col3:float", "col4:double", "col5:int64", "col6:string"]
        indexs: [index2:col2:col5]
        rows:
          #  col0, col1, col2, col3, col4, col5, col6
          - [ 0,   1,     5,   1.1,  11.1,  1,   1 ]
          - [ 0,   2,     5,   2.2,  22.2,  2,   22 ]
          - [ 1,   3,     55,  3.3,  33.3,  1,   333 ]
          - [ 1,   4,     55,  4.4,  44.4,  2,   4444 ]
          - [ 2,   5,     55,  5.5,  55.5,  3,   aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa]
      - name: t2
        columns: ["str0:string", "str1:string", "col3:float", "col4:double", "col2:int16", "col1:int32", "col5:int64"]
        indexs: [index1:col2:col5]
        rows:
          #  str0, str1, col3, col4, col2, col1, col5
          - [ 2,  EEEEE, 5.5,  55.5, 550,   5,   3]
          - [ 1,  DDDD,  4.4,  44.4, 550,   4,   2]
          - [ 1,  CCC,   3.3,  33.3, 550,   3,   1]
          - [ 0,  BB,    2.2,  22.2, 50,    2,   2]
          - [ 0,  A,     1.1,  11.1, 50,    1,   1]
   ```
