### ISSUE TITLE
When the index is latest, data expiration is wrong

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#704]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion
When the index is latest, the data expiration is wrong, and there is one more piece of data than expected

## Expected Behavior
        - [2,"aa", 1, 1590738990000]
        - [4,"aa", 1, 1590738990000]

## Current Behavior
 ---- ---- ---- ---------------
  id   c1   c2   c3
 ---- ---- ---- ---------------
  4    aa   1    1590738990000
  2    aa   1    1590738990000
  1    aa   1    1590738990000
 ---- ---- ---- ---------------

1.  create table auto_VCeOIIKA( id int, c1 string, c2 int, c3 timestamp, c4 timestamp, index(key=(c1),ts=c4))options(partitionnum=1,replicanum=1);
2.  insert into auto_VCeOIIKA values
(1,'aa',1,1590738990000,1637047962096);
insert into auto_VCeOIIKA values
(2,'aa',1,1590738990000,1637047962096);
insert into auto_VCeOIIKA values
(3,'aa',1,1590738990000,1637047962096);
insert into auto_VCeOIIKA values
(4,'aa',1,1590738990000,1637048562097);
3. CREATE INDEX index1 ON auto_VCeOIIKA (c2) OPTIONS (ts=c4, ttl=(10m,2), ttl_type=absandlat);
4. select id,c1,c2,c3 from auto_VCeOIIKA where c2 = 1;

## case
```yaml
  -
    id: 23
    desc: 指定ttl_type=absandlat,部分数据过期
    inputs:
      -
        columns: ["id int","c1 string","c2 int","c3 timestamp", "c4 timestamp"]
        indexs: ["index1:c1:c4"]
        rows:
          - [1,"aa", 1, 1590738990000,"{currentTime}-600001"]
          - [2,"aa", 1, 1590738990000,"{currentTime}-600001"]
          - [3,"aa", 1, 1590738990000,"{currentTime}-600001"]
          - [4,"aa", 1, 1590738990000,"{currentTime}"]
    sqls:
      - CREATE INDEX index1 ON {0} (c2) OPTIONS (ts=c4, ttl=(10m,2), ttl_type=absandlat);
      - select id,c1,c2,c3 from {0} where c2 = 1;
    expect:
      columns: ["id int","c1 string","c2 int","c3 timestamp"]
      order: id
      rows:
        - [3,"aa", 1, 1590738990000]
        - [4,"aa", 1, 1590738990000]
```

>
