### ISSUE TITLE
The following case failed to execute in the cluster cli mode

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#736]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

The following case failed to execute in the cluster cli mode

## Expected Behavior
        - [1,"aa",30]
        - [2,"aa",31]
        - [5,"aa",67]

## Current Behavior
![wecom-temp-c70c3744ef1c95c597a7d08681169e0f](https://user-images.githubusercontent.com/18275570/142366287-b4a28afa-ade4-4de8-8679-736292e50dd7.png)

## case

```yaml
  -
    id: 21
    desc: union+maxsize+INSTANCE_NOT_IN_WINDOW
    inputs:
      -
        columns : ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1590738990000,"2020-05-01"]
          - [2,"aa",21,31,1.2,2.2,1590738990001,"2020-05-01"]
          - [5,"aa",24,34,1.5,2.5,1590738990004,"2020-05-02"]
      -
        columns : ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [3,"aa",22,32,1.3,2.3,1590738990002,"2020-05-01"]
          - [4,"aa",23,33,1.4,2.4,1590738990003,"2020-05-01"]
    sql: |
      SELECT id, c1, sum(c4) OVER w1 as w1_c4_sum FROM {0} WINDOW
      w1 AS (UNION {1} PARTITION BY {0}.c1 ORDER BY {0}.c7 ROWS_RANGE BETWEEN 3 PRECEDING AND CURRENT ROW MAXSIZE 2 INSTANCE_NOT_IN_WINDOW);
    expect:
      order: id
      columns: ["id int","c1 string","w1_c4_sum bigint"]
      rows:
        - [1,"aa",30]
        - [2,"aa",31]
        - [5,"aa",67]
```
## case path
OpenMLDB/cases/function/window/test_maxsize.yaml
