### ISSUE TITLE
The following case failed to execute in the cluster cli mode

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#738]
## Expected Behavior
        - [1,"aa",20,32,32]
        - [2,"aa",21,32,64]
        - [3,"aa",22,32,64]
        - [4,"bb",23,34,34]
        - [5,"bb",24,34,68]

## Current Behavior
![image](https://user-images.githubusercontent.com/18275570/142372619-e36455e5-0e8b-4101-b621-b6575d9d0d5d.png)

## case
```yaml
  -
    id: 23-1
    desc: lastjoin结合maxsize
    inputs:
      -
        columns : ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1590738990000,"2020-05-01"]
          - [2,"aa",21,31,1.2,2.2,1590738990001,"2020-05-02"]
          - [3,"aa",22,32,1.3,2.3,1590738990002,"2020-05-03"]
          - [4,"bb",23,33,1.4,2.4,1590738990003,"2020-05-04"]
          - [5,"bb",24,34,1.5,2.5,1590738990004,"2020-05-05"]
      -
        columns: ["id int","c1 string","c3 int","c4 bigint","c5 float","c6 double","c7 timestamp","c8 date"]
        indexs: ["index1:c1:c7"]
        rows:
          - [1,"aa",20,30,1.1,2.1,1590738990000,"2020-05-01"]
          - [2,"aa",20,31,1.1,2.1,1590738990001,"2020-05-01"]
          - [3,"aa",20,32,1.1,2.1,1590738990002,"2020-05-01"]
          - [4,"bb",20,33,1.1,2.1,1590738990003,"2020-05-01"]
          - [5,"bb",21,34,1.2,2.2,1590738990004,"2020-05-02"]
    sql: |
      select {0}.id,{0}.c1,{0}.c3,{1}.c4,
      sum({1}.c4) OVER w1 as w1_c4_sum
      from {0}
      last join {1} ORDER BY {1}.c7 on {0}.c1={1}.c1
      WINDOW
      w1 AS (PARTITION BY {0}.c1 ORDER BY {0}.c7 ROWS_RANGE BETWEEN 3 PRECEDING AND CURRENT ROW MAXSIZE 2)
      ;
    expect:
      order: id
      columns: ["id int","c1 string","c3 int","c4 bigint","w1_c4_sum bigint"]
      rows:
        - [1,"aa",20,32,32]
        - [2,"aa",21,32,64]
        - [3,"aa",22,32,64]
        - [4,"bb",23,34,34]
        - [5,"bb",24,34,68]
```

## case path
OpenMLDB/cases/function/window/test_maxsize.yaml
