### ISSUE TITLE
The following cases will fail in request mode

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#749]
The following cases will fail in request mode

## Expected Behavior
        - [ "aa",2,13,1590738989000 ]
        - [ "bb",21,131,1590738990000 ]
        - [ "cc",41,151,1590738992000 ]

## Current Behavior
execute failed

## case
```yaml
  - id: 9
    desc: 使用子查询查不同库的数据然后lastjoin
    mode: request-unsupport
    tags: ["request 模式有问题，@chenjing"]
    db: db
    inputs:
      - columns: [ "c1 string","c2 int","c3 bigint","c4 timestamp" ]
        db: db1
        indexs: [ "index1:c1:c4" ]
        rows:
          - [ "aa",2,3,1590738989000 ]
          - [ "bb",21,31,1590738990000 ]
          - [ "cc",41,51,1590738991000 ]
      - columns: [ "c1 string","c2 int","c3 bigint","c4 timestamp" ]
        db: db2
        indexs: [ "index1:c1:c3" ]
        rows:
          - [ "aa",2,13,1590738989000 ]
          - [ "bb",21,131,1590738990000 ]
          - [ "cc",41,151,1590738992000 ]
    sql: select db.t1.c1,db.t1.c2,db.t2.c3,db.t2.c4 from (select * from db1.{0}) as t1 last join (select * from db2.{1}) as t2 ORDER BY db.t2.c3 on db.t1.c1=db.t2.c1;
    expect:
      order: c1
      columns: [ "c1 string","c2 int","c3 bigint","c4 timestamp" ]
      rows:
        - [ "aa",2,13,1590738989000 ]
        - [ "bb",21,131,1590738990000 ]
        - [ "cc",41,151,1590738992000 ]
```
## case path
/OpenMLDB/cases/function/multiple_databases/test_multiple_databases.yaml
